### PR TITLE
Misc. implementations

### PR DESCRIPTION
**Pull request by dmirmilshteyn**
Here is a batch of somewhat-random implementations for missing stuff that I've encountered, as well as a basic verison of TypeInfo (#799)

### CODE REVIEW

**Comment by kg** [comment]
Looks good. If tests pass I'll merge it. Thanks!

**Comment by dmirmilshteyn** [comment]
Guess I didn't test thoroughly enough for the DefinedTypes/IsAssignableFrom implementation. JSIL.GetTypesFromAssembly returns types that are not initialized (__TypeInitialized__ is false). I'm guessing that type initialization is what sets the value of __AssignableTypes__, which is null if used directly from Assembly.DefinedTypes and breaks IsAssignableFrom. Should I check if they have been initialized, and if they haven't, call JSIL.InitializeType on them?

**Comment by kg** [comment]
A type should automatically get initialized before you have access to it. It's fine to call InitializeType on a single type object if you need it to be initialized (like to have that AssignableTypes table). Just don't batch call it on a bunch of types.

For the record, InitializeType runs the static constructor(s).

**Comment by dmirmilshteyn** [comment]
Alright, that should be it!

**Comment by kg** [comment]
This has a bunch of conflicts, probably because I waited too long to merge it. ;-(

**Comment by dmirmilshteyn** [comment]
I'll make a new PR. Merging this with the newly split files will be tricky.

**Pull request closed without merging**
