### PR TITLE
Improved source map generation

### PR DESCRIPTION
**Pull request by iskiselev**
With this PR source map generated by JSIL is much more usable.

### CODE REVIEW

**Comment by iskiselev** [comment]
As with this PR source map generated by JSIL will be usable for most tasks, we probably should create separate wiki page with information about it or mention it somewhere else - to make more people know about this flag.

**Comment by iskiselev** [comment]
Probably we may think how to integrate them into TryJSIL, so that end-user will have an option with which he'll be able to see/debug original C# source in browser developer tools.

**Comment by kg** [comment]
Does this depend on any preceding PRs?

**Comment by iskiselev** [comment]
No, This PR contains all required commits.

**Comment by kg** [comment]
I assume this passes without the spidermonkey bug in effect?

**Comment by iskiselev** [comment]
Yes, the only failed test is Spidermonkey's array sort.

**Pull request merged**
