### PR TITLE
Net 4.5 single platform configuration

### PR DESCRIPTION
**Pull request by iskiselev**
Projects migrated to 4.5, all projects are target AnyCpu now.
Created Compiler.Executor.32bit.cspoj that compiles jsilc as 32 bit application.

Per discussions in #793, #796.

### CODE REVIEW

**Comment by iskiselev** [comment]
I've added also Travis-CI initial support (and some small fixes to achieve it).
@kg, if you'll merge it, you need just login to https://travis-ci.org/ with github account and enable CI for JSIL project (it will crate hook on repository to start build after push/pull request).

Currently I only build it and run SimpleTest (original, with ignored bcl). We have a number of failed tests - all F# tests (fsprojects/FSharp.Compiler.CodeDom#8) and some other tests. We really need to look on non-F# tests.

**Comment by kg** [comment]
Thanks for doing all this. I really appreciate it.

**Comment by kg** [comment]
I think I enabled Travis CI

**Comment by iskiselev** [comment]
Great! We'll see it on next commit.

**Pull request merged**
