### PR TITLE
Refresh: Dynamic on JS side 

### PR DESCRIPTION
**Pull request by iskiselev**
This PR is refreshed version of #925 and #935. It also includes #957 and ILSpy updated to latest version. Please use this one instead of other three (I've closed them).

With merging this Roslyn-compiled sources should work good. This PR is "breaking change", as it changes JS-interop results to object from dynamic (but they could be casted to dynamic and still work as before).

### CODE REVIEW

**Comment by kg** [comment]
Do you mind filing a bookkeeping PR for me to follow up and update the examples? (As-is they'll be fine because Try is running a build I prepare manually, so that it doesn't break every time I commit.)

**Comment by kg** [comment]
```
/home/travis/build/sq/JSIL/JSIL.sln: error : Could not find the project file '/home/travis/build/sq/JSIL/Upstream/ILSpy/NRefactory/ICSharpCode.NRefactory/ICSharpCode.NRefactory.csproj'

		Configuration: Release Platform: AnyCPU
```

**Comment by iskiselev** [comment]
Fixed all build problems. TravisCI still reports as broken due Mozilla problem (#956).

**Comment by iskiselev** [comment]
Please wait a little bit before merging, looks like I found some small issues.

**Comment by iskiselev** [comment]
Everything is OK, could be merged.

**Comment by kg** [comment]
Thanks a lot for the hard work on this

**Pull request merged**
