### PR TITLE
Translated BCL (begin)

### PR DESCRIPTION
**Pull request by iskiselev**
Here is fix for #784 and start real work on Translated BCL configuration. Here in Translated BCL configuration HashSet and Dictionary use translated implementation. Test for Stubbed/Translated BCL use correct Bootstap file. Added temporary workaround for passing "Environment" info in script.

### CODE REVIEW

**Comment by iskiselev** [comment]
Added fix for #785.

**Comment by iskiselev** [comment]
A lot of additional changes:
1. Process inner types for CorlibTypes (CorlibTypes are types that don't go to output, defined in JavascriptFormatter).
2. Added field TypeReferenceContext.EnclosingTypeSkipped, that is used instead of ShouldSkipMember delegate in JavascriptFormatter, that allow me to do (1).
3. Revised Translated/Stubbed simple tests. Now all Simple tests are run under all configurations, BCL assemblies (mscorlib/System/System.Core) translated once per test group execution.
4. Fixed most problems in Translated/Stubbed simple tests.

Please look on Proxies.BCL\System.cs. Here is a group of ignored class to be able to translate System assembly, otherwise JSIL fails.
Not all Simple Tests pass under new configurations, but it is not critical - this number is small (around 10) and I'll work to fix them :).

**Comment by kg** [comment]
Thanks for doing all this. Hopefully I'll have some time and energy this weekend to merge this PR

**Comment by iskiselev** [comment]
All tests except one fixed. Last one is broken due #789.
Updated browser test runner. To run TranslatedBcl test use something like: Path:///ToJSIL/test_runner.html?bclMode=translated&autoRun#Tests/SimpleTestCases/ReflectionMemberType.cs.out;Tests/Bootstappers/BclBootstrapTranslated.cs.out

**Comment by kg** [comment]
With this merged hundreds of tests are failing with 'TestFixtureSetUp failed in SimpleTestCasesForTranslatedBcl' and I don't know how to get the diagnostic output. Any ideas?

**Comment by iskiselev** [comment]
Sounds very strange... It worked for me. According to this output, looks there was problem in TestFixtureSetUp, that should translate all BCL libraries. Could you try to click in Resharper right on Test class name and check if there is any output?

**Comment by kg** [comment]
I don't use resharper anymore, it kept breaking things. I'm using the VS2015 test runner. I'll see if I can find the fixture output... usually it shows it if there is any.

**Comment by kg** [comment]
```
// .ctor: Accessing System.UInt16 System.Net.UnsafeNclNativeMethods/HttpApi/HTTP_COOKED_URL::AbsPathLength without a reference as this.
// .ctor: Accessing System.UInt16* System.Net.UnsafeNclNativeMethods/HttpApi/HTTP_COOKED_URL::pQueryString without a reference as this.
// .ctor: Accessing System.UInt16 System.Net.UnsafeNclNativeMethods/HttpApi/HTTP_COOKED_URL::QueryStringLength without a reference as this.
// .ctor: Accessing System.UInt16* System.Net.UnsafeNclNativeMethods/HttpApi/HTTP_COOKED_URL::pQueryString without a reference as this.
// .ctor: Accessing System.UInt16 System.Net.UnsafeNclNativeMethods/HttpApi/HTTP_COOKED_URL::QueryStringLength without a reference as this.
error
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding)
   at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
   at JSIL.TranslationResult.WriteToString() in C:\Users\Katelyn\Documents\Projects\JSIL\JSIL\TranslationResult.cs:line 93
   at JSIL.Tests.ComparisonTest.<>c.<GenerateJavascript>b__39_1(TranslationResult tr) in C:\Users\Katelyn\Documents\Projects\JSIL\Tests\ComparisonTest.cs:line 487
   at JSIL.Tests.ComparisonTest.Translate[TOutput](Func`2 processResult, Func`1 makeConfiguration, Action`1 onTranslationFailure, Action`1 initializeTranslator, Nullable`1 scanForProxies) in C:\Users\Katelyn\Documents\Projects\JSIL\Tests\ComparisonTest.cs:line 442
   at JSIL.Tests.ComparisonTest.GenerateJavascript(String[] args, String& generatedJavascript, Int64& elapsedTranslation, Func`1 makeConfiguration, Boolean throwOnUnimplementedExternals, Action`1 onTranslationFailure, Action`1 initializeTranslator, Nullable`1 scanForProxies, Boolean shouldWritePrologue) in C:\Users\Katelyn\Documents\Projects\JSIL\Tests\ComparisonTest.cs:line 486
   at JSIL.Tests.GenericTestFixture.RunComparisonTest(String filename, String[] stubbedAssemblies, TypeInfoProvider typeInfo, Action`2 errorCheckPredicate, List`1 failureList, String commonFile, Boolean shouldRunJs, AssemblyCache asmCache, Func`1 makeConfiguration, Action`1 onTranslationFailure, JSEvaluationConfig evaluationConfig, String compilerOptions, Action`1 initializeTranslator, Func`1 getTestRunnerQueryString, Nullable`1 scanForProxies, String[] extraDependencies) in C:\Users\Katelyn\Documents\Projects\JSIL\Tests\GenericTestFixture.cs:line 281
SetUp failed for test fixture JSIL.SimpleTests.SimpleTestCasesForTranslatedBcl
SetUp : System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding)
   at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
   at JSIL.TranslationResult.WriteToString() in C:\Users\Katelyn\Documents\Projects\JSIL\JSIL\TranslationResult.cs:line 93
   at JSIL.Tests.ComparisonTest.<>c.<GenerateJavascript>b__39_1(TranslationResult tr) in C:\Users\Katelyn\Documents\Projects\JSIL\Tests\ComparisonTest.cs:line 487
   at JSIL.Tests.ComparisonTest.Translate[TOutput](Func`2 processResult, Func`1 makeConfiguration, Action`1 onTranslationFailure, Action`1 initializeTranslator, Nullable`1 scanForProxies) in C:\Users\Katelyn\Documents\Projects\JSIL\Tests\ComparisonTest.cs:line 442
   at JSIL.Tests.ComparisonTest.GenerateJavascript(String[] args, String& generatedJavascript, Int64& elapsedTranslation, Func`1 makeConfiguration, Boolean throwOnUnimplementedExternals, Action`1 onTranslationFailure, Action`1 initializeTranslator, Nullable`1 scanForProxies, Boolean shouldWritePrologue) in C:\Users\Katelyn\Documents\Projects\JSIL\Tests\ComparisonTest.cs:line 486
   at JSIL.Tests.GenericTestFixture.RunComparisonTest(String filename, String[] stubbedAssemblies, TypeInfoProvider typeInfo, Action`2 errorCheckPredicate, List`1 failureList, String commonFile, Boolean shouldRunJs, AssemblyCache asmCache, Func`1 makeConfiguration, Action`1 onTranslationFailure, JSEvaluationConfig evaluationConfig, String compilerOptions, Action`1 initializeTranslator, Func`1 getTestRunnerQueryString, Nullable`1 scanForProxies, String[] extraDependencies) in C:\Users\Katelyn\Documents\Projects\JSIL\Tests\GenericTestFixture.cs:line 294
   at JSIL.Tests.GenericTestFixture.RunSingleComparisonTestCase(Object[] parameters, Func`1 makeConfiguration, JSEvaluationConfig evaluationConfig, Action`1 onTranslationFailure, String compilerOptions, Action`1 initializeTranslator, Func`1 getTestRunnerQueryString, Nullable`1 scanForProxies, String[] extraDependencies, Boolean shouldRunJs) in C:\Users\Katelyn\Documents\Projects\JSIL\Tests\GenericTestFixture.cs:line 420
   at JSIL.SimpleTests.SimpleTestCasesForTranslatedBcl.SetupFixture() in C:\Users\Katelyn\Documents\Projects\JSIL\Tests\SimpleTestCasesForTranslatedBcl.cs:line 66
NUnit VS Adapter 2.0.0.0 executing tests is finished
```

Hm.

**Comment by iskiselev** [comment]
I have no access to computer with studio right now. Honestly I've never tried VS2015 test runner - will do it tomorrow. Do I need any special plugin for it?
Could you start debugging test case from it?
I've seen once or twice OutOfMemory exception. Probably you've got it. It always helped me just restarting testes. Really in this case all SimpleTestCasesForTranslatedBcl should fail (if 'TestFixtureSetUp' failed they even was not started.)

**Comment by kg** [comment]
Yeah, they're all failing because the fixture setup fails. So that's to be expected. It looks like everything else passed.

**Comment by iskiselev** [comment]
Yes, I guess right! We see it probably because I've added System.dll to translation. Also #765 may affected it. Maybe we should run tests with x64 JSIL?

**Comment by iskiselev** [comment]
Is this fails every time? I've seen it once or twice - but I've run it successfully dozens of times.

**Comment by iskiselev** [comment]
The most interesting, will it fail if it will be the only TestCase group that you will run in same session (don't know how much VS2015 test runner shares per executions). Could you try to run it in fresh VS instance?

**Comment by kg** [comment]
It happens consistently even with a new VS instance. It seems to always happen here:

```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding)
   at System.Text.UTF8Encoding.GetString(Byte[] bytes, Int32 index, Int32 count)
   at JSIL.TranslationResult.WriteToString() in C:\Users\Katelyn\Documents\Projects\JSIL\JSIL\TranslationResult.cs:line 93
   at JSIL.Tests.ComparisonTest.<>c.<GenerateJavascript>b__39_1(TranslationResult tr) in C:\Users\Katelyn\Documents\Projects\JSIL\Tests\ComparisonTest.cs:line 487
```

So maybe the problem is just that the mechanism we're using to write the JS behaves poorly for large amounts of text... naive buffer size doubling, perhaps?

**Comment by iskiselev** [comment]
Sounds interesting. We really outputs a lot of data to single string here. Which is much worse, we even do:
```
translatedJs = "(function() {" + Environment.NewLine + translatedJs + Environment.NewLine + "})()";
var tempFilename = Path.GetTempFileName();
File.WriteAllText(tempFilename, translatedJs + Environment.NewLine + invocationJs);
```
We really should rewrite it to use streams/StringBuilder and it may solve all memory problems.

**Comment by iskiselev** [comment]
When you've complain last time in #768, does you mean that you always have OutOfMemoryException? As I've never seen it I've supposed that was interim.

**Comment by kg** [comment]
It actually worked this time when I attached a debugger and ran it, but the heap size crossed 2GB. We probably just need to overhaul that part of the test infrastructure since it was never designed for a use case like this. Make it write to a file instead of building strings.

**Comment by kg** [comment]
Something else that's probably worth doing is making sure JSILc more aggressively purges unnecessary data if we're going to be doing full mscorlib+System compiles in test runs like this. I'm not sure how much of this it already does - ideally the JS generation stage will discard the function ASTs as soon as they're no longer needed, ILSpy data will be purged from RAM, etc. I suspect the compiler 'leaks' some data like this since under normal circumstances it wouldn't be a problem.

**Comment by iskiselev** [comment]
Probably it is right time to setup projects with x64 build also? I fully agree that we should look on memory usage and fix test run infrastructure/JSIL internals, but x64 build will be much faster solution for now.

**Comment by kg** [comment]
I agree, but I'm not sure how easy it is to run the vs unit test runner as 64-bit. I'll look into it when I have time.

On August 9, 2015 10:26:46 PM PDT, Igor Kiselev <notifications@github.com> wrote:
>Probably it is right time to setup projects with x64 build also? I
>fully agree that we should look on memory usage and fix test run
>infrastructure/JSIL internals, but x64 build will be much faster
>solution for now.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sq/JSIL/pull/786#issuecomment-129307033

- kg (mobile)

**Comment by iskiselev** [comment]
Also, probably we need some CI that will run all test cases? Translated test cases runs long enough to annoy running all them manually on each check in. Probably we could run manually only smaller set of tests (really interesting how to select them? Only SimpleTests with ignoring BCL?)

Do you know any free CI servers for open source? I'll investigate this question also.

**Pull request merged**
