### PR TITLE
Same caching metadata resolver

### PR DESCRIPTION
**Pull request by iskiselev**
@kg, please answer #763. This is suggest patch if it was a bug.

### CODE REVIEW

**Comment by kg** [comment]
That sounds like a bug. The intent of the caching resolver is to only do it once ever, I think?

There might be a reason you can't, like per-assembly things that influence assembly resolution? A CLR2 assembly pulls in mscorlib 2.0 and a CLR4 assembly pulls in 4.0? But I'm not sure we care, since mixing corlibs is a huge problem as-is and I don't even know how it works on native .NET :-)

**Comment by kg** [comment]
I notice you touched the ComparisonTest initialization. Are you sure you meant to do that? The cache reuse from before was a huge optimization for tests and it looks like you're changing it to create a new instance of something for every test run instead of re-using an existing one.

**Comment by iskiselev** [comment]
@kg, in this PR I've tried to fully preserve logic of test - earlier tests shared `AssemblyCache`, but each of it used each own CachingMetadataResolver/AssemblyResolver, as it was created inside `GetReaderParameters.AssemblyTranslator` (once per assembly load). Now it should work totally same - new instance of this classes are created once per test, but still share `AssemblyCache` between test.

But while I've typed it, I found one potential problem - we still may use different `CachingMetadataResolver` in testing environment - if mscorlib was loaded in earlier test, but probably it is much less critical - as JSIL code use special logic for comparing `MemberDefinition`, and DCE tests are isolated, but according to this it still may be a good idea implementing custom comparer for them.

**Comment by iskiselev** [comment]
Other option may be changing test logic and also use same `CachingMetadataResolver` in tests. The only problem of this decision that I see is increase of memory usage by tests. This could be resolved by implementing Assembly unload option.

**Pull request merged**
