### PR TITLE
Header for generated scripts, generated scripts are readonly

### PR DESCRIPTION
**Pull request by iskiselev**
Header for generated scripts, generated scripts are readonly (#818).

### CODE REVIEW

**Comment by kg** [comment]
5>C:\Users\Katelyn\Documents\Projects\ilwasm\third_party\JSIL\JSIL.Libraries\Targets\MSBuild.Gulp.targets(55,9): warning : [21:45:09] 'metascript' errored after 624 ms
5>C:\Users\Katelyn\Documents\Projects\ilwasm\third_party\JSIL\JSIL.Libraries\Targets\MSBuild.Gulp.targets(55,9): warning : [21:45:09] Error: EEXIST, mkdir 'C:\Users\Katelyn\Documents\Projects\ilwasm\third_party\JSIL\Libraries'
5>C:\Users\Katelyn\Documents\Projects\ilwasm\third_party\JSIL\JSIL.Libraries\Targets\MSBuild.Gulp.targets(55,9): warning : at Error (native)
5>C:\Users\Katelyn\Documents\Projects\ilwasm\third_party\JSIL\JSIL.Libraries\Targets\MSBuild.Gulp.targets(56,9): error : Error running gulp task 'build-Debug'. See Warnings for details.

**Comment by iskiselev** [comment]
Will check in few minutes.

**Comment by iskiselev** [comment]
Sorry for that, I'm only learning gulp and it worked sometimes :).

**Comment by kg** [comment]
Not a problem :-)

**Pull request merged**
