### PR TITLE
Javascript files splitted

### PR DESCRIPTION
**Pull request by iskiselev**
Here is continue work of splitting JS files per class base. With this commit all files that I wanted to split were spitted, so it will be easier to markup it for Translated/Stubbed version and a little bit reorganize (move some parts to different files).

This commit is also critical for fast merge, as otherwise it will be hard to merge changes with unsplitted version.

### CODE REVIEW

**Comment by iskiselev** [comment]
Sorry, I found that I missed some files. Please wait before merging it, it's not ready yet.

**Comment by iskiselev** [comment]
Looks that now this PR is completed and safe for merge.

**Comment by iskiselev** [comment]
@kg, can you comment on it? There already appeared some merged conflicts. I could rebase this on current master, but I will not waste time if you don't want merge it or prefer to do it later.

**Comment by kg** [comment]
Did you do anything other than split the .js files apart? This diff is too big for me to actually review, but if all you did is split files out and tests pass, I'll merge it. Sorry I never got to it before.

**Comment by iskiselev** [comment]
Here I've done only splitting JS files and reordered some of them to keep declaration and external implementation near each other. In JSIL.IO.js I was need to introduce three versions at the same time, as it prior conditionally declare some classes only based on presence of translated/stubbed mscorlib.

**Comment by iskiselev** [comment]
I'll rebase it this evening in such case, thank you! I always try to note in PR all changes that I've made :)

**Comment by iskiselev** [comment]
Rebased, but have not run all test cases on new version yet. So let's wait at least Travis-CI and I'll run all tests later today and confirm it here.

**Comment by iskiselev** [comment]
All test passed, safe to merge :)

**Pull request merged**
