### PR TITLE
JS-interop functions return object

### PR DESCRIPTION
**Pull request by iskiselev**
It is next part for #925 (and include that PR).
JS-interop return object instead of dynamic now.

Probably we need update samples used for TryJSIL, but I don't know where they are located.

### CODE REVIEW

**Comment by kg** [comment]
What did you update the submodules to point to?

**Comment by iskiselev** [comment]
With latest commit from sq/JSIL.Meta NoDynamic branch (b185a3d1a30e6d580456e6d78eaf07f0b06a13bb)

**Comment by kg** [comment]
As long as it's not pointing towards JSIL.Meta master, can you also merge this into a branch on sq/JSIL? I want to switch all the master branches over wholesale at once.

**Comment by iskiselev** [comment]
Sure. Will push it to branch NoDynamic.

**Comment by iskiselev** [comment]
Done.

**Pull request closed without merging**
